# Generated by Django 3.1.7 on 2022-06-06 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0017_auto_20220602_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryMember',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=30, verbose_name='Memeber first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Memeber last name')),
                ('membership_start_date', models.DateField(default=datetime.datetime(2022, 6, 6, 20, 9, 53, 712145, tzinfo=utc), verbose_name='MemberShip start date')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='lang',
            field=models.ManyToManyField(help_text='Choose a languages you write with ', to='catalog.Languages'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.librarymember'),
        ),
    ]
