# Generated by Django 3.1.7 on 2022-06-07 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20220606_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.librarymember'),
        ),
        migrations.AlterField(
            model_name='librarymember',
            name='membership_start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 7, 5, 49, 48, 639936, tzinfo=utc), verbose_name='MemberShip start date'),
        ),
    ]
