# Generated by Django 3.1.7 on 2022-06-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20220607_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryMember',
        ),
    ]
